spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ****
    username: kotlin_master
    password: ****

#paimentprocessing:
#  kafka:
#    consumer:
#      bootstrapServers: ${spring.embedded.kafka.brokers}
#      groupId: testGroup
#      topic: testTopic

