spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://tinkoff-kotlin-psql-1.postgres.database.azure.com:5432/fintech?currentSchema=cashback
    username: kotlin_master
    password: koklin

kafka:
  consumer:
    bootstrap-servers: 40.69.78.245:19092
    topic: transactions
    group-id: cashback
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      request.timeout.ms: 10000

service:
  client:
    url: http://13.79.17.165/client-service/api/v1/client/{id}
  card:
    url: http://13.79.17.165/card-service/api/v1/card/{id}
  loyalty:
    url: http://13.79.17.165/loyalty-service/api/v1/program/{id}
  notification:
    url: http://13.79.17.165/notification-service/api/v1/client/{clientId}/message


